name: vishal
favicon: null
layout_spectrum: 0.20304457726888359
typography_spectrum: 0.06164602842181921
title: Vishal Burathoki
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#262262'
    - '#ffffff'
    - '#000000'
    - '#a7c9d9'
    - '#8482a6'
  brandStrength: 0.5049857166595757
  lightness: 0.41376123926602304
  saturation: 0.7283904675859958
  rhythmicContrast: 0.7719682925380766
purpose: []
